# Generated by Django 5.2.8 on 2025-11-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='statut_en_cours',
            field=models.BooleanField(default=False),
        ),
    ]
