# Generated by Django 5.2.9 on 2025-12-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taches', '0002_tache_statut_en_cours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tache',
            name='completee',
        ),
        migrations.AlterField(
            model_name='tache',
            name='statut_en_cours',
            field=models.BooleanField(default=True),
        ),
    ]
